import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import store from "@/store/store";
import { Provider } from "react-redux";
import { Store } from "lucide-react";
import StoreProvider from "./storeProvider";
import ViewportProvider from "./viewPortProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <ViewportProvider>
            <div
              className="fixed inset-0 flex flex-col overflow-hidden"
              style={{ height: "var(--app-height)" }}
            >
              {children}
            </div>
          </ViewportProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
